### ISSUE TITLE
Update RBE docker image

### ISSUE THREAD

**Issue by alan-agius4** [angular/dev-infra#1017]
Update docker image in https://github.com/angular/dev-infra/blob/main/bazel/remote-execution/BUILD.bazel#L21 to address GLIBC related errors ex `/b/f/w/bazel-out/k8-fastbuild/bin/packages/ngtools/webpack/webpack_test_node18.sh.runfiles/node18_linux_amd64/bin/nodejs/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version ;GLIBC_2.28' not found` when using RBE with Nodejs 18.

**Comment by devversion** [comment]
@alan-agius4 Updated with https://github.com/angular/dev-infra/commit/0ce0aafaa677851a3f432da1f29556b99a9ada13

**Comment by alan-agius4** [comment]
Great thanks.
