### ISSUE TITLE
Consider cleaning up file system copy util for stackblitz

### ISSUE THREAD

**Issue by devversion** [angular/dev-infra#1688]
This is directly pulled from the blossom version, I will leave it for now with a TODO to follow up since I am unsure of there was something else at play.

_Originally posted by @josephperrott in https://github.com/angular/dev-infra/pull/1686#discussion_r1414494328_

**Comment by josephperrott** [comment]
After more investigation, I believe that it is worth keeping the code as is for the time being.  It is useful to have this code handle the renaming of package.json and ensuring that the TMP directory infinite recursion does not occur.
