### ISSUE TITLE
More visibility for missing CLAs for contributors

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/dev-infra#374]
When a first-time contributor creates a PR, there is a need to sign a CLA. Currently, there is a CI check that verifies that the CLA is present and a contributor needs to click the "Details" link to go to a page that contains further details. I believe for new contributors this is not obvious enough and people don't sign CLA without extra messages from the team (so it's an additional overhead for reviewers to ask PR author to sign a CLA).

The proposal is for a bot to post a comment on the PR to notify a contributor that the CLA is not signed and we can not proceed. In this case a contributor will receive a notification and likely follow the instructions.

**Comment by AndrewKushnir** [comment]
Example PR: https://github.com/angular/angular/pull/44793

**Comment by josephperrott** [comment]
Closing as discussed offline, this issue will need to be created in the GoogleBots issue reporting.
