### ISSUE TITLE
Create a new Job on Angular which would run profiling tests

### ISSUE THREAD

**Issue by mhevery** [angular/dev-infra#65]
See: https://github.com/angular/angular/pull/33186

I would like to have a separate circle-ci job which would execute the `profile_all.js` to measure if the PR is making things better or worse.
1. Revert PR in job and run `profile_all.js --write baseline.json`
2. Restore PR in job and run `profile_all.js --read baseline.json`

For now this is enough to see if the number are stable/predictable.

**Comment by gkalpak** [comment]
I suggest we skip this (to save time/resources) if the changes could not have affected the numbers (e.g. when changes are outside `packages/` or changes are inside `aio/` only - whatever criterion makes sense).

**Comment by josephperrott** [comment]
Closing as this is no longer being investigated
