### ISSUE TITLE
"PR action: rerun CI at HEAD" label doesn't trigger rebuilds on angular/angular

### ISSUE THREAD

**Issue by IgorMinar** [angular/dev-infra#69]
When I apply "PR action: rerun CI at HEAD" label to a pr on a/a repo, I see that the ng-bot removes the label (as expected), but doesn't trigger a rebuild of the PR on CircleCI.

Is there a known reason why this fails? Could this be fixed?

**Comment by josephperrott** [comment]
This has been fixed.

**Comment by josephperrott** [comment]
This has been fixed.
