### ISSUE TITLE
Disallow feature commit messages without a scope

### ISSUE THREAD

**Issue by kara** [angular/dev-infra#72]
Example: `feat: make mocha a zone module. (#34719)`

All feature commits should have a scope. This has been problematic in angular/angular because some scopes should be omitted from the CHANGELOG (e.g. zone.js), but they can't be if the scope isn't listed.

The validation task that we use should catch this case and throw.

**Comment by josephperrott** [comment]
This has already been fixed in our commit message validation rollout.
