### ISSUE TITLE
Easy way to sync Github issues to Jira

### ISSUE THREAD

**Issue by kara** [angular/dev-infra#73]
We've been doing a lot of manual porting from Github to Jira, which is probably not a good use of time. In the past, we had a Github label that we could apply if we wanted to sync something to Jira, which was super convenient. I think there may have been permissions issues that prevented us from doing this long-term, but it would be great if we could revisit how this might be possible.

**Comment by josephperrott** [comment]
Closing as we no longer rely on Jira for this tracking.
